version: '3.8'
services: 
  mongo1:
    container_name: mongo1
    image: mongo:latest
    networks:
      common.network:
    ports:
      - 20000:27017
    volumes:
      - mongo1.vol:/data/db
      # - ./rs-init.sh:/scripts/rs-init.sh
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]
 
  mongo2:
    container_name: mongo2
    image: mongo:latest
    networks:
      common.network:
    ports:
      - 20001:27017
    depends_on:
      - mongo1
    volumes:
      - mongo2.vol:/data/db
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]
 
  mongo3:
    container_name: mongo3
    image: mongo:latest
    networks:
      common.network:
    ports:
      - 20002:27017
    depends_on:
      - mongo1     
    volumes:
      - mongo3.vol:/data/db
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]


networks:
  common.network:
    driver: bridge
 
volumes:
  mongo1.vol:
    name: "mongo1"
 
  mongo2.vol:
    name: "mongo2"
 
  mongo3.vol:
    name: "mongo3"